version: '3.1'

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3,apigateway,sqs,lambda,secretsmanager
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - ./test/aws:/etc/localstack/init/ready.d
      - ./dist:/dist
      - "/var/run/docker.sock:/var/run/docker.sock"
