# Setup Settings
POST {{endpoint}} HTTP/1.1
content-type: application/json;charset=utf-8

{
  "action": "settings",
  "tenant": "localhost",
  "payload": {
    "slackChannelId": "{{slackChannelId}}",
    "slackToken": "{{slackToken}}",
    "preview": {
      "baseURL": "{{authorUrl}}",
      "authorization": "Basic {{authorBasic}}",
      "external": "{{authorExternalUrl}}"
    },
    "live": {
      "baseURL": "{{publishUrl}}",
      "external": "{{publishExternalUrl}}"
    }
  }
}

###

# Store in preview
POST {{endpoint}} HTTP/1.1
content-type: application/json;charset=utf-8

{
  "action": "store",
  "tenant": "localhost",
  "relPath": "a/b/c",
  "mode": "preview"
}

###

###
# Evict object in preview
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "action": "evict",
  "tenant": "local",
  "relPath": "a/b/c",
  "mode": "preview"
}
