# Setup Settings
POST {{endpoint}} HTTP/1.1
content-type: application/json;charset=utf-8

{
  "action": "settings",
  "tenant": "localhost",
  "payload": {
    "preview": {
      "baseURL": "https://2d56-92-184-124-150.ngrok-free.app",
      "authorization": "Basic ZnJhbmtsaW4taW5nZXN0b3I6MTIzNA=="
    },
    "live": {
      "baseURL": "https://29fe-92-184-124-150.ngrok-free.app"
    }
  }
}

###

# Store payload in preview
POST {{endpoint}} HTTP/1.1
content-type: application/json;charset=utf-8

{
    "action": "store",
    "tenant": "1ddae356422974932f5f02946a3f2670d782ac7eae55edb32e4b9b65f7d",
    "relPath": "a/b/c",
    "mode": "preview",
    "payload": {
        "data": {
            "id": "test-data-id",
            "prop1": "value1",
            "prop2": 1000
        }
    }
}

###

# Cleanup variations in preview
POST {{endpoint}} HTTP/1.1
content-type: application/json;charset=utf-8

{
  "action": "evict",
  "tenant": "localhost",
  "relPath": "aem/validation/fragment-h-1",
  "mode": "preview"
}

###
# Evict object in preview
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "action": "evict",
    "tenant": "local",
    "relPath": "a/b/c",
    "mode": "preview"
}

###

# Copy existing preview to live
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "action": "store",
    "tenant": "local",
    "relPath": "a/b/c",
    "mode": "live"
}

###

# Evict existing live object
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "action": "evict",
    "tenant": "wknd",
    "relPath": "en/adventures/all-adventures",
    "mode": "preview"
}
